# Made on Linux
# Now also tested on Mac
all:
	mkdir -p assets
	mkdir -p assets/linux_cupspdfs
	mkdir -p assets/linux_cupspdfs/vector
	mkdir -p assets/linux_cupspdfs/raster
	mkdir -p assets/macos_pdfwriter
	mkdir -p assets/macos_pdfwriter/vector
	mkdir -p assets/macos_pdfwriter/raster
	node ./printing-test-cases.js
