name: build

on: [push, pull_request]

jobs:
  ubuntu:
    permissions: {}
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        java: [25]
        #arch: [x86_64, aarch64, riscv64]
        arch: [x86_64]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'liberica'
      - run: sudo apt-get install makeself
      - run: ant -Dtarget.arch=${{ matrix.arch }} makeself
      - uses: actions/upload-artifact@v7
        with:
          name: qz-tray-linux-${{ matrix.arch }}
          path: out/qz-tray-*.run
      - if: ${{ matrix.arch == 'x86_64' }}
        run: |
          # Only run tests on same arch
          sudo apt-get install firefox chromium
          ant testng
          # Run policy tests again, but as root
          sudo JAVA_HOME="$JAVA_HOME" JAVACMD="$JAVA_HOME/bin/java" ant -Dtestng.pattern="**/policy/**" testng
          sudo DEBUG=true out/qz-tray-*.run
          /opt/qz-tray/qz-tray --version
          sudo apt-get install nsis
          ant nsis

      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Run Autotests
        if: ${{ matrix.arch == 'x86_64' }}
        run: |
          # Install Deps
          sudo apt-get install -y ghostscript imagemagick

          # Setup printer (CUPS)
          sudo apt-get remove -yqq cups cups-pdf
          sudo apt-get install -yqq cups-bsd cups-pdf cups-client
          sudo service cups start

          # Make the PDF folder
          mkdir "$HOME/PDF"

          # Run Autotest
          cd autotest
          npm install
          node test-run/start-tray.js

      - name: Upload Generated Prints (Linux)
        if: always() && matrix.arch == 'x86_64'
        uses: actions/upload-artifact@v4
        with:
          name: prints-linux-${{ matrix.arch }}
          path: autotest/latest/
          if-no-files-found: ignore

      - name: Upload Diff Artifacts (Linux)
        if: always() && matrix.arch == 'x86_64'
        uses: actions/upload-artifact@v4
        with:
          name: diff-results-linux-${{ matrix.arch }}
          path: autotest/diff/
          if-no-files-found: ignore

  macos:
    runs-on: [macos-latest]
    strategy:
      matrix:
        java: [25]
        #arch: [x86_64, aarch64]
        arch: [aarch64]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'liberica'
      - run: ant -Dtarget.arch=${{ matrix.arch }} pkgbuild
      - uses: actions/upload-artifact@v7
        with:
          name: qz-tray-macos-${{ matrix.arch }}
          path: out/qz-tray-*.pkg
      - if: ${{ matrix.arch == 'aarch64' }}
        run: |
          # Only run tests on same arch
          brew install --cask google-chrome firefox
          ant testng
          # Run policy tests again, but as root
          sudo ant -Dtestng.pattern="**/policy/**" testng
          sudo installer -pkg out/qz-tray-*.pkg -target / || (cat /tmp/qz-install.log && false)
          "/Applications/QZ Tray.app/Contents/MacOS/QZ Tray" --version
          brew install nsis makeself
          ant makeself
          ant nsis

      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Run Autotests
        if: ${{ matrix.arch == 'aarch64' }}
        run: |
          # Install Deps
          # /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install ghostscript imagemagick

          # Setup printer (PDFWriter)
          curl -fLs -O https://github.com/rodyager/RWTS-PDFwriter/releases/latest/download/RWTS-PDFwriter.pkg
          sudo installer -pkg RWTS-PDFwriter.pkg -target /
          sudo mkdir -p /private/var/spool/pdfwriter/$USER
          sudo chown $USER:staff /private/var/spool/pdfwriter/$USER

          # Install Node (simplified for script)
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
          \. "$HOME/.nvm/nvm.sh"
          nvm install 24

          # Run Autotest
          cd autotest
          npm install
          node test-run/start-tray.js

      - name: Debug CUPS logs
        if: failure()
        run: sudo tail -n 100 /var/log/cups/error_log

      - name: Upload Generated Prints (MacOS)
        if: always() && matrix.arch == 'aarch64'
        uses: actions/upload-artifact@v4
        with:
          name: prints-macos-${{ matrix.arch }}
          path: autotest/latest/
          if-no-files-found: ignore

      - name: Upload Diff Artifacts (MacOS)
        if: always() && matrix.arch == 'aarch64'
        uses: actions/upload-artifact@v4
        with:
          name: diff-results-macos-${{ matrix.arch }}
          path: autotest/diff/
          if-no-files-found: ignore

  windows:
    runs-on: [windows-latest]
    strategy:
      matrix:
        java: [25]
        arch: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'liberica'
      - run: choco install nsis --no-progress
      - run: ant "-Dtarget.arch=${{ matrix.arch }}" nsis
      - uses: actions/upload-artifact@v7
        with:
          name: qz-tray-windows-${{ matrix.arch }}
          path: out/qz-tray-*.exe
      - if: ${{ matrix.arch == 'x86_64' }}
        run: |
          # Only run tests on same arch
          choco install firefox googlechrome
          ant testng
          Start-Process -Wait ./out/qz-tray-*.exe -ArgumentList "/S"
          "&'C:/Program Files/QZ Tray/qz-tray.exe' --wait --version|Out-Null"

      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Run Autotests
        if: ${{ matrix.arch == 'x86_64' }}
        shell: powershell
        run: |
          # $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://www.bullzip.com/download/pdf/Setup_BullzipPDFPrinter_2025_2_0_2990.exe" -OutFile "setup.exe"
          Start-Process -FilePath ".\setup.exe" -ArgumentList "/VERYSILENT /ACCEPT_EULA" -Wait
          New-Item -Type Directory -Force "$env:AppData\PDF Writer\Bullzip PDF Printer"; "[PDF Printer]`n  output=$env:UserProfile\PDF\<smarttitle>.pdf`n  confirmoverwrite=no`n  confirmnewfolder=no`n  appendifexists=no`n  openfolder=no`n  showpdf=no`n  showsaveas=nofile`n  showsettings=no`n  suppresserrors=yes`n" | Set-Content "$env:AppData\PDF Writer\Bullzip PDF Printer\settings.ini" -Encoding UTF8
          New-Item -Type Directory -Force "$env:UserProfile\PDF"

          # Restart-Service Spooler -Force
          # Start-Sleep -Seconds 5
          Get-Printer -Name "Bullzip PDF Printer"

          powershell -c "irm https://community.chocolatey.org/install.ps1|iex"
          refreshenv

          choco install nodejs --version="24.14.0" -y --no-progress
          # A prereq for ghostscript, apparently comes with the windows-latest image
          choco install vcredist2013 -y --no-progress
          choco install nsis ghostscript -y --no-progress

          winget install -e --id ImageMagick.ImageMagick --accept-package-agreements --accept-source-agreements --silent

          refreshenv
          # TODO: Why won't 'gm' recognize by PowerShell?
          # Try to influence the GITHUB_PATH so 'gm' will be recognized
          $updatedPath = [Environment]::GetEnvironmentVariable("Path", "Machine")
          echo "$updatedPath" >> $env:GITHUB_PATH

          cd autotest
          npm install
          set DEBUG=gm
          node test-run\start-tray.js
      - name: Upload Generated Prints (Windows)
        if: always() && matrix.arch == 'x86_64'
        uses: actions/upload-artifact@v4
        with:
          name: prints-win-${{ matrix.arch }}
          path: autotest/latest/
          if-no-files-found: ignore

      - name: Upload Diff Artifacts (Windows)
        if: always() && matrix.arch == 'x86_64'
        uses: actions/upload-artifact@v4
        with:
          name: diff-results-win-${{ matrix.arch }}
          path: autotest/diff/
          if-no-files-found: ignore
